-- apply changes
create table urls (
  id                            integer generated by default as identity not null,
  created_at                    timestamptz not null,
  name                          varchar(255),
  constraint pk_urls primary key (id)
);

