-- apply changes
create table url (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  created_at                    timestamp not null,
  constraint pk_url primary key (id)
);

create table check (
  id                            bigint generated by default as identity not null,
  status_code                   integer not null,
  title                         varchar(255),
  h1                            varchar(255),
  description                   clob,
  url_id                        bigint not null,
  created_at                    timestamp not null,
  constraint pk_check primary key (id)
);

-- foreign keys and indices
create index ix_check_url_id on check (url_id);
alter table check add constraint fk_check_url_id foreign key (url_id) references url (id) on delete restrict on update restrict;

